src/main/java/com/loanservice/domain/LoanTypeEntity.java
package com.loanservice.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.Table;


@Entity
@Table(name = "LOAN_TYPE")
public class LoanTypeEntity
    extends AbstractAutoIdEntity {

    private static final long serialVersionUID = -3620787349048486318L;
    public static final String ATTR_maxterm = "maxTerm";
    public static final String ATTR_minterm = "minTerm";
    public static final String ATTR_expireDate = "expireDate";
    public static final String ATTR_status = "status";
    public static final String ATTR_maxamount = "maxAmount";
    public static final String ATTR_minamount = "minAmount";
    public static final String ATTR_percent = "percent";

    @Column(name = "NAME")
    private String name;

    @Column(name = "MAX_TERM")
    private Integer maxTerm;

    @Column(name = "MIN_TERM")
    private Integer minTerm;

    @Column(name = "PERCENT")
    private Double percent;

    @Column(name = "EXPIRE_DATE")
    private Date expireDate;

    @Enumerated
    @Column(name = "STATUS")
    private Status status;

    @Column(name = "MAX_AMOUNT")
    private Double maxAmount;

    @Column(name = "MIN_AMOUNT")
    private Double minAmount;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getMaxTerm() {
        return maxTerm;
    }

    public void setMaxTerm(Integer maxTerm) {
        this.maxTerm = maxTerm;
    }

    public Integer getMinTerm() {
        return minTerm;
    }

    public void setMinTerm(Integer minTerm) {
        this.minTerm = minTerm;
    }

    public Double getPercent() {
        return percent;
    }

    public void setPercent(Double percent) {
        this.percent = percent;
    }

    public Date getExpireDate() {
        return expireDate;
    }

    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Double getMinAmount() {
        return minAmount;
    }

    public void setMinAmount(Double minAmount) {
        this.minAmount = minAmount;
    }

    @Override
    public String toString() {
        final StringBuffer buffer = new StringBuffer();
        buffer.append("Name=" + this.getName());
        buffer.append(";");
        buffer.append("percent=" + this.getPercent());
        buffer.append("%.");

        return buffer.toString();
    }

    public String getString() {
        return toString();
    }
} // end class LoanTypeEntity

src/main/java/com/loanservice/domain/RequestEntity.java
package com.loanservice.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


@Entity
@Table(name = "REQUEST")
public class RequestEntity
    extends AbstractAutoIdEntity {

    public static final long serialVersionUID = 6402521929217517161L;
    public static final String ATTR_clientId = "clientId";
    public static final String ATTR_ip = "ip";
    public static final String ATTR_attemptDate = "attemptDate";

    @Column(name = "ATTEMPT_DATE")
    private Date attemptDate;

    @Column(name = "TERM")
    private Integer term;

    @Column(name = "AMOUNT")
    private Double amount;

    @Column(name = "CLIENT_ID")
    private Integer clientId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID", insertable = false, updatable = false)
    private ClientEntity client;

    @Column(name = "LOAN_TYPE_ID")
    private Integer loanId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOAN_TYPE_ID", insertable = false, updatable = false)
    private LoanTypeEntity loan;

    @Column(name = "MESSAGE")
    @Enumerated
    private ErrorCode errorCode;

    @Column(name = "IP")
    private String ip;

    public RequestEntity() { }

    public RequestEntity(Date attemptDate, Integer term, Double amount, Integer clientId, String ip) {
        this.attemptDate = attemptDate;
        this.term = term;
        this.amount = amount;
        this.clientId = clientId;
        this.ip = ip;

    }

    public Date getAttemptDate() {
        return attemptDate;
    }

    public void setAttemptDate(Date attemptDate) {
        this.attemptDate = attemptDate;
    }

    public Integer getTerm() {
        return term;
    }

    public void setTerm(Integer term) {
        this.term = term;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public LoanTypeEntity getLoan() {
        return loan;
    }

    public void setLoan(LoanTypeEntity loan) {
        this.loan = loan;
    }

    public Integer getClientId() {
        return clientId;
    }

    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    public ClientEntity getClient() {
        return client;
    }

    public void setClient(ClientEntity client) {
        this.client = client;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public ErrorCode getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(ErrorCode errorCode) {
        this.errorCode = errorCode;
    }

    public String getMessage() {
        return (errorCode != null) ? errorCode.getMessage() : "";
    }

    public Integer getLoanId() {
        return loanId;
    }

    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }
} // end class RequestEntity

src/main/webapp/WEB-INF/pages/form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Create Request Form</title>
<style>
  <%@include file='../css/main.css'%>
</style>
</head>
<body>
  <center>
    <form:form id="registerForm" modelAttribute="request" method="post" action="register">
      <table class="requestTable">
        <tr>
          <td />
          <td style="text-align: center;"><div class="title">New request</div></td>
        </tr>
        <tr>
          <td><form:label path="clientName" class="label">Name</form:label></td>
          <td><form:input path="clientName" value="${requestObject.clientName}" /></td>
        </tr>
        <tr>
          <td />
          <td><form:errors path="clientName" class="error" /></td>
        </tr>
        <tr>
          <td><form:label path="clientSurname" class="label">Surname</form:label></td>
          <td><form:input path="clientSurname" value="${requestObject.clientSurname}" /></td>
        </tr>
        <tr>
          <td />
          <td><form:errors path="clientSurname" class="error" /></td>
        </tr>        
        <tr>
          <td><form:label path="term" class="label">Number of months</form:label></td>
          <td><form:input path="term" value="${requestObject.term}" /></td>
        </tr>
        <tr>
          <td />
          <td><form:errors path="term" class="error" /></td>
        </tr>
        <tr>
          <td><form:label path="amount" class="label">Amount</form:label></td>
          <td><form:input path="amount" value="${requestObject.amount}" /></td>
        </tr>
        <tr>
          <td />
          <td><form:errors path="amount" class="error" /></td>
        </tr>
        <tr>
          <td></td>
          <td style="text-align: center;">
            <input class="submit" type="submit" value="Send request" width="50px;" />
          </td>
        </tr>
        <tr>
          <td></td>
          <td style="text-align: center;">
            <input class="submit" onClick="parent.location='listip'" type="button" value="This IP requests" width="200px;" />
          </td>
        </tr>        
        <tr>
          <td />
          <td style="text-align: center;"><div class="title">Operation response</div></td>
        </tr>
        <tr>
          <td />
          <td><textarea readonly rows="5" cols="10">${exception}</textarea></td>
        </tr>
      </table>
    </form:form>
  </center>
</body>
</html>

src/main/webapp/WEB-INF/pages/list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Request list</title>
<style>
  <%@include file='../css/main.css'%>
</style>
</head>
<body>
  <center>
    <div class="title">Request list</div>
    <c:if test="${!empty requestList}">
      <table width="600px">
        <tr>
          <th>Date</th>
          <th>Client</th>
          <th>Term</th>
          <th>Amount</th>
          <th>Loan Type</th>
          <th>Message</th>
        </tr>
        <c:forEach items="${requestList}" var="request">
          <tr>
            <td><fmt:formatDate value="${request.attemptDate}" pattern="yyyy-MM-dd HH:mm:ss" /></td>
            <td><c:out value="${request.client.name} ${request.client.surname}" /></td>
            <td><c:out value="${request.term}" /></td>
            <td><c:out value="${request.amount}" /></td>
            <td><c:out value="${request.loan.string}" /></td>
            <td><c:out value="${request.message}" /></td>
          </tr>
        </c:forEach>
      </table>
    </c:if>
    <input class="submit" onClick="parent.location='form'" type="button" value="Click Here to add new Request" width="200px;" />
  </center>
</body>
</html>